### ISSUE TITLE
meek与tor内置的有什么区别？

### ISSUE THREAD

**Issue by renyouguo** [yinghuocho/firefly-proxy#10]
1、是否实现了meek的自动IP搜索？就像XX-Net在gae上做的那样。否则Tor自带的meek的速度实在是太慢了。
2、无法负载均衡？不能实现一个代理无法连接时自动切换到下一个代理的话，意义有限啊。

**Comment by yinghuocho** [comment]
这个是SOCKS 的，不走 Tor network, 应该比 Tor 快一些．

不太明白你指的负载均衡是什么意思，防 block还是提高速度？

欢迎试用反馈，谢谢！

**Comment by renyouguo** [comment]
负载均衡就是指多个代理同时生效，多线程链接。
这样即使某个或几个代理失效了，不会影响到继续穿越。
可参考Android上的fqrouter.

**Comment by yinghuocho** [comment]
这个功能有的
