### ISSUE TITLE
请教 20151 端口是什么用途？

### ISSUE THREAD

**Issue by helloworker** [yinghuocho/firefly-proxy#11]
翻墙代理设置项目下，有一个 本地地址 127.0.0.1 端口 20151 ，这个项目是什么意思，什么用途？谢谢！

**Comment by yinghuocho** [comment]
这个是真正用来翻墙的代理端口．

Firefly 有两层代理．20149 (http) 和 20150 (socks) 是第一层，在第一层代理会查黑名单或其他辅助功能，确定需要翻墙才会转到第二层 20151 (socks) 的翻墙代理．

**Comment by helloworker** [comment]
明白了，谢谢！
