### ISSUE TITLE
ubuntu下，关闭firefly 所在的shell后，其他软件都不能正常用网

### ISSUE THREAD

**Issue by huguyuehuhu** [yinghuocho/firefly-proxy#116]
ubuntu下，关闭firefly 所在的shell后，其他软件都不能正常用网，只有重新开启firefly 才恢复怎么解决？谢谢

**Comment by BearJean** [comment]
笨蛋呀，你在shell打开的命令后面加一个&就可以了，否则关闭shell之后进程会被杀掉当然会连不上。

**Comment by huguyuehuhu** [comment]
谢谢你的解答，可能我表述不清，我说关闭后不能用网络，并不是说不能翻墙。这个我已经搞定了，我把这个问题关了吧，以前搞忘关了。

**Comment by BearJean** [comment]
此笨蛋是溺爱语气，没有恶意.……^-^
