### ISSUE TITLE
关于代理设置的疑问

### ISSUE THREAD

**Issue by AlwaysWithYou** [yinghuocho/firefly-proxy#13]
开发者，你好！我也有问题想请教一下：在<a href='http://127.0.0.1:20160/proxy'>http://127.0.0.1:20160/proxy</a>中有一个“翻墙代理”，默认是127.0.0.1:20151，我试了几次后，发现这也是个socks5代理，请问这个代理与“本地代理”中的socks5代理有何不同？紧随其下是可选的一些通道，所以这个是专门用来连接meek服务器的吗？
firefly中选用本地代理并且浏览器中设为全局代理的话，可以访问那些被屏蔽的网站，但在ip.cn查ip的话，是自己原来的ip，选用全局+“翻墙代理”组合再查确实成了海外的。那么firefly是有个内置的白名单吗？
![firefly](https://cloud.githubusercontent.com/assets/9449136/8124897/f1185aaa-1112-11e5-949e-01f37849e9a9.png)

**Comment by yinghuocho** [comment]
Firefly 用两级代理加黑名单的方式分发流量．如果设置为本地代理，浏览器会转发到本地代理，然后查询黑名单，只有需要翻墙的网站才会通过翻墙代理转发，其他的网站直接从本地访问．

建议使用本地代理加黑名单的方式．黑名单应该还是比较全的，而且可以自己定制．

**Comment by AlwaysWithYou** [comment]
感谢解答！
