### ISSUE TITLE
捐款渠道可以改改

### ISSUE THREAD

**Issue by laurel-he** [yinghuocho/firefly-proxy#192]
比特币和那什么是有门槛的，弄个微信啊支付宝的捐款渠道不行么

**Comment by ZimmerWu** [comment]
要实名

**Comment by Zzy0706** [comment]
微信支付宝比较危险吧

**Comment by EGZJY** [comment]
忘了 ShadowsocksR 作者咋被人肉的？！账单都拉了出来

**Comment by egzhongjian** [comment]
可选给作者当比特币矿工来捐赠。23333

2018-05-14 10:21 GMT+08:00 刘能 <notifications@github.com>:

**Comment by egzhongjian** [comment]
How Bitcoin Mining Works https://www.bitcoinmining.com/
Description

Let your computer earn you money with Bitcoin Miner, the free easy-to-use
Bitcoin miner! Earn Bitcoin which can be exchanged for real-world currency!
Works great at home, work, or on the go. Download Bitcoin Miner and start
mining Bitcoin today!
Get File:
https://www.microsoft.com/en-us/store/p/bitcoin-miner/9wzdncrdhxb6

**Comment by xfmniao** [comment]
see tihs! https://www.v2ray.com/chapter_00/cpu.html

**Comment by laurel-he** [comment]
没用过比特币的人表示有点儿虚，总觉得比特币涨得好夸张
