### ISSUE TITLE
速度问题

### ISSUE THREAD

**Issue by V-zhangyunxiang** [yinghuocho/firefly-proxy#253]
为什么现在付费的还不如之前免费时候的速度了，速度太慢了。youutbe ，网页等等。本人网络没问题，北京联通

**Comment by yinghuocho** [comment]
@V-zhangyunxiang  现在客户端的服务器选择可能有点问题，选不到最快的服务器，后面我们会增加功能客户端直接指定服务器。另外同时也在寻找新的服务器资源。希望这些事情做好以后能有改善。

**Comment by rexlightman** [comment]
加油啊 我是付费用户 但是这几天速度慢 不断线但是连不上网络 希望以后情况能有改善
