### ISSUE TITLE
关闭这个之后，所有网页都打不开了

### ISSUE THREAD

**Issue by bannedbook** [yinghuocho/firefly-proxy#3]
不是太明白这个产品原理，反正关闭这个之后，所有网页都打不开了，网银也打不开，再打开萤火虫，网银就能开了

**Comment by yinghuocho** [comment]
萤火虫会自动设置代理，正常情况下关闭以后应该会回复代理设置的．可能是哪里出了问题，能不能详细说一下是什么浏览器，怎么关的？

**Comment by helloworker** [comment]
建议： 是否自动更改代理设置，还是留给用户自己选择吧。

**Comment by yinghuocho** [comment]
有配置选项的，配置界面选择不自动打开浏览器就不会自动更改代理设置．

默认自动更改代理主要还是考虑安全没有技术背景的翻墙网友，可以安装完后直接使用．

**Comment by yinghuocho** [comment]
有一个 bug 导致关闭浏览器时没有恢复 IE 原来的代理设置，已经修正了．谢谢！
