### ISSUE TITLE
PC端登陆不可以吗？

### ISSUE THREAD

**Issue by Benbinbin** [yinghuocho/firefly-proxy#339]
我在家里的笔记本注册付费购买的账号，换成异地其他的笔记本登陆就不可以吗？
我是帮别人注册购买的.
他反映说手机的可以使用，但笔记本PC端不能登陆，提示“Incorrect username or password"
请问有解决方案吗？

**Comment by yinghuocho** [comment]
没有限制的，应该就是用户名密码输入错误，注意大小写空格这些都要一样的。
