### ISSUE TITLE
iOS怎么下载？中国区美国区都不行啊

### ISSUE THREAD

**Issue by jcglqmoyx** [yinghuocho/firefly-proxy#465]
iOS怎么下载？下载不了啊？
![652d91804fe8d79ef301234269615a2](https://user-images.githubusercontent.com/38204621/56078142-36504600-5e17-11e9-8e6b-2619faab84c4.jpg)
![b404ee049b8cbbdb7eb927c9c4a541d](https://user-images.githubusercontent.com/38204621/56078144-3b14fa00-5e17-11e9-92a7-3dc120d66c42.jpg)

**Comment by jcglqmoyx** [comment]
请问怎样才能下载呢

**Comment by knightshaw** [comment]
我也想知道，开发者不会弃疗了吧

**Comment by knightshaw** [comment]
反馈无数次了，估计是完全放弃iOS了。但是那个下载链接还留在那误导人真的很无语
