### ISSUE TITLE
XP下报错

### ISSUE THREAD

**Issue by StrollStars** [yinghuocho/firefly-proxy#5]
在XP下运行报如下错误，是不支持XP还是运行库问题？

cx_Freeze: Python error in main script
---------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "main.py", line 333, in <module>
  File "main.py", line 330, in main
  File "main.py", line 184, in run
  File "main.py", line 60, in recover_conf
  File "C:\Python27\lib\shutil.py", line 119, in copy
  File "C:\Python27\lib\shutil.py", line 82, in copyfile
IOError: [Errno 2] No such file or directory: u'D:\\firefly-proxy-win-0.2.0\\config.json.last'

**Comment by yinghuocho** [comment]
你好，正常情况下是不会出现这个问题的，你是直接下载，然后解压缩运行？

可能有什么异常．可以运行 firefly.exe --debug 然后看看 firefly.log 文件中有什么错误信息．

**Comment by StrollStars** [comment]
嗯，如你所说，是直接解压运行的。奇怪的是加了调试参数后，可以正常启动了，显示了一堆如下格式错误：
[Hosts]: 
::1 localhost
提供了一个无效的参数。

其中第二行在变化，基本是“IPV6 域名”的格式。再次启动程序就不报错直接退出了。
在调试模式下关闭Hosts翻墙，依旧不能常规模式启动，并且该关闭会被重新开启。

**Comment by ottojiang** [comment]
@StrollStars [Hosts] 错误是因为没有 IPv6 支持，应该不影响正常使用的．重新开启是因为启动失败，试图恢复上次启动的配置．

用调试参数启动以后，再用常规模式的异常应该是不同的，能不能帮忙把那个报错信息贴一下，谢谢！

**Comment by yinghuocho** [comment]
@StrollStars [Hosts] 报错是因为不支持 IPv6，应该不影响正常启动的．考虑到有些误导，以后会把这个从错误信息里去掉．

Hosts 翻墙开启是因为启动失败会尝试恢复上次启动的配置．

在调试模式下启动了以后，再常规模式启动报错应该是不一样的．能不能帮忙把最后的错误信息贴一下．谢谢！

**Comment by StrollStars** [comment]
调试模式关闭后再正常模式启动，程序没有任何反应退出。日志文件也是如上述内容，没有改变。
再次运行调试模式，文件尾部出现如下内容：
The handshake operation timed out
meek relay (https://a0.awsstatic.com/,dswpv736infni.cloudfront.net) is not valid

**Comment by yinghuocho** [comment]
@StrollStars timeout 应该也不会影响的．

改了一下输出，
请下载这个运行看看错误信息是什么：
https://github.com/yinghuocho/download/blob/master/debug/firefly-proxy-win-0.2.0-issue5.zip?raw=true

谢谢．

**Comment by StrollStars** [comment]
运行正常，还需要加--debug参数看么？
release中的amazonaws.com下载不容易，希望以后能换其他地址。

**Comment by yinghuocho** [comment]
不用了，谢谢．

release 下的地址被封了，放在那里只是存档用的．
wiki 上的链接墙内应该可以直接访问．

**Comment by StrollStars** [comment]
嗯，我发现下载似乎是整个GitHub的问题。

**Comment by yinghuocho** [comment]
@StrollStars github release 上的链接会重定向到 amazon s3, amazon s3 被封了．

**Comment by StrollStars** [comment]
嗯，猜测和Tor的MeeK有关。有不重定向的方法吗？

**Comment by yinghuocho** [comment]
不知道, 好像没有.
