### ISSUE TITLE
Firefly-darwin 0.4.7无故消耗巨大CPU资源

### ISSUE THREAD

**Issue by chenzww** [yinghuocho/firefly-proxy#51]
如图，新版firefly会在使用一段时间后陷入永久地占用绝大多数的CPU资源，不重启不消停，即使不再用代理。
![firefly-cpu](https://user-images.githubusercontent.com/1970731/27011170-df88d01a-4ee8-11e7-92fa-2e15fcbd677e.png)
![firefly-energy](https://user-images.githubusercontent.com/1970731/27011171-e3087d94-4ee8-11e7-89f7-0e09dfd2aaa6.png)

**Comment by jzp820927** [comment]
其他系统有类似情况麽？

**Comment by yinghuocho** [comment]
@chenzww  截屏显示是0.4.6，是升级以后出现的？

**Comment by chenzww** [comment]
我用的是macOS Sierra。其它系统未用过。
Mac的「活动监视器」显示的是Firefly 0.4.6，而其配置页面则显示的是「Firefly-darwin 0.4.7」。

**Comment by chenzww** [comment]
原本用的是0.4.6，不知何时自动升级到了0.4.7。

**Comment by chenzww** [comment]
我原本用的是0.4.6，不知何时自动升级到0.4.7。

**Comment by yinghuocho** [comment]
客户端有自动升级的功能，可以在配置里面关掉

**Comment by hardass** [comment]
發現同樣的問題，macos 10.12.5
機器MacBook Air (11-inch, Late 2010)

**Comment by yinghuocho** [comment]
谢谢反馈，我要调试一下看看能不能重现

**Comment by hardass** [comment]
謝謝，具體重現的方法是運行後打開safari測試聯通後，合上屏幕，過上一小時或者一整晚，打開機器登陸，就會發現此進程始終保持將cpu 100%。如果您需要幫助，可以考慮加入一些運行日誌輸出，編譯一個版本給我，我試試看能否生成一些有用的信息給您參考。

**Comment by yinghuocho** [comment]
@hardass 试了一下，找到一个其他的问题，但是没有看到cpu100%的情况出现。请帮忙调试一下，terminal 进入 /Applications/Firefly.app/Contents/MacOS，运行 ./firefly 就会有日志。

**Comment by hardass** [comment]
早上起來就又發現這個問題，貌似沒有什麼異常的日誌。
如果不關閉程序重啓，cpu會一直被它佔用。

![screen shot 2017-06-19 at 7 55 49 am](https://user-images.githubusercontent.com/1505281/27265288-28df7ec6-54c5-11e7-90d9-cbf08202d5b4.png)

這些是從昨晚合上蓋子到今早打開蓋子間的控制台輸出，請參考
[log.txt](https://github.com/yinghuocho/firefly-proxy/files/1083487/log.txt)

**Comment by yinghuocho** [comment]
@chenzww 谢谢，你发的日志里没有看到什么异常信息，我再看看。

**Comment by yinghuocho** [comment]
@hardass 谢谢，日志看不出来什么问题，我再看看。

**Comment by yinghuocho** [comment]
之前的一个改动有bug，但是还是不知道为什么会导致CPU占用过高。刚刚更新了一个版本改回去了，请更新一下看看还有没有同样的问题。

**Comment by jzp820927** [comment]
不会是 MAC 特有的问题吧？

**Comment by hardass** [comment]
謝謝，新的版本這幾天用下來沒有再出現過之前的問題了。

**Comment by yinghuocho** [comment]
@hardass 谢谢反馈
