### ISSUE TITLE
CPU占用率超高

### ISSUE THREAD

**Issue by wooowooo** [yinghuocho/firefly-proxy#55]
在经过一段youtube-dl的下载,然后中断后,下载已退出.这时发现cpu占用率达60%.

> 2017/07/07 19:54:12 report google analytics event: [client launch]
> 2017/07/07 19:54:12 tunnel proxy (SOCKS) listens on 127.0.0.1:34417
> 2017/07/07 19:54:12 SOCKS proxy listens on 127.0.0.1:38250
> 2017/07/07 19:54:12 HTTP/S proxy listens on 127.0.0.1:38251
> DEBUG i18n: translate.go:103 Setting locale zh-CN
> 2017/07/07 19:54:12 settings url: http://127.0.0.1:38252/nd3h9hoey9xgs12288lywi0cfyrkaxge/settings
> 
> (firefly_linux_amd64:18249): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
> 2017/07/07 19:54:56 pipe listener starts
> 2017/07/07 19:54:56 SocketPipe Create: pipe socket connections: 2
> 2017/07/07 19:54:56 SocketPipe Create: pipe socket connections: 4
> 2017/07/07 19:54:56 SocketPipe Create: pipe socket connections: 6
> 2017/07/07 19:54:56 SocketPipe Create: pipe socket connections: 8
> 2017/07/07 19:54:56 SocketPipe Create: pipe socket connections: 10
> 2017/07/07 19:54:56 SocketPipe Create: pipe socket connections: 12
> 2017/07/07 19:54:56 SocketPipe Create: pipe socket connections: 14
> 2017/07/07 19:54:56 SocketPipe Create: pipe socket connections: 16
> 2017/07/07 19:54:56 sendRecv error: certificate name does not match: https://104.20.49.34:lbsportsinvestment.com
> 2017/07/07 19:54:57 SocketPipe Create: pipe socket connections: 18
> 2017/07/07 19:54:57 SocketPipe Create: pipe socket connections: 20
> 2017/07/07 19:54:57 SocketPipe Create: pipe socket connections: 22
> 2017/07/07 19:54:57 SocketPipe Create: pipe socket connections: 24
> 2017/07/07 19:54:57 SocketPipe Create: pipe socket connections: 26
> 2017/07/07 19:54:58 SocketPipe Create: pipe socket connections: 28
> 2017/07/07 19:54:58 SocketPipe Create: pipe socket connections: 30
> 2017/07/07 19:54:58 SocketPipe Create: pipe socket connections: 32
> 2017/07/07 19:54:58 SocketPipe Create: pipe socket connections: 34
> 2017/07/07 19:54:58 SocketPipe Create: pipe socket connections: 36
> 2017/07/07 19:54:58 connected to peer: https://104.16.38.170,cf.gofirefly.org,line1|2637
> 2017/07/07 19:54:58 mux Client established.
> 2017/07/07 19:54:58 report google analytics event: [client connect-succ]
> 2017/07/07 19:54:58 SocketPipe Create: pipe socket connections: 38
> 2017/07/07 19:54:58 cmd connect
> 2017/07/07 19:54:59 SocketPipe 10 Close: pipe socket connections: 37
> 2017/07/07 19:54:59 duplexSendLoop: outbound stream closed
> 2017/07/07 19:54:59 SocketPipe 18 Close: pipe socket connections: 36
> 2017/07/07 19:54:59 duplexSendLoop: outbound stream closed
> 2017/07/07 19:54:59 SocketPipe 11 Close: pipe socket connections: 35
> 2017/07/07 19:55:00 sendRecv error: remote error: tls: handshake failure
> 2017/07/07 19:55:00 duplexRecvLoop: error roundTrip: write: connection reset by peer
> 2017/07/07 19:55:00 SocketPipe 19 Close: pipe socket connections: 34
> 2017/07/07 19:55:00 duplexRecvLoop: error roundTrip: write: connection reset by peer
> 2017/07/07 19:55:00 SocketPipe 24 Close: pipe socket connections: 33
> 2017/07/07 19:55:00 duplexSendLoop: outbound stream closed
> 2017/07/07 19:55:00 SocketPipe 26 Close: pipe socket connections: 32
> 2017/07/07 19:55:00 duplexSendLoop: outbound stream closed
> 2017/07/07 19:55:00 SocketPipe 25 Close: pipe socket connections: 31
> 2017/07/07 19:55:01 SocketPipe 14 Close: pipe socket connections: 30
> 2017/07/07 19:55:01 duplexSendLoop: outbound stream closed
> 2017/07/07 19:55:01 SocketPipe 6 Close: pipe socket connections: 29
> 2017/07/07 19:55:01 duplexSendLoop: outbound stream closed
> 2017/07/07 19:55:01 SocketPipe 15 Close: pipe socket connections: 28
> 2017/07/07 19:55:01 duplexRecvLoop: error roundTrip: write: connection reset by peer
> 2017/07/07 19:55:01 SocketPipe 27 Close: pipe socket connections: 27
> 2017/07/07 19:55:01 sendRecv error: malformed HTTP response "15a1"
> 2017/07/07 19:55:01 SocketPipe 7 Close: pipe socket connections: 26
> 2017/07/07 19:55:01 duplexRecvLoop: error roundTrip: write: connection reset by peer
> 2017/07/07 19:55:01 duplexRecvLoop: error roundTrip: write: connection reset by peer
> 2017/07/07 19:55:01 duplexRecvLoop: error roundTrip: write: connection reset by peer
> 2017/07/07 19:55:02 sendRecv error: remote error: tls: handshake failure
> 2017/07/07 19:55:02 sendRecv error: remote error: tls: handshake failure
> 2017/07/07 19:55:02 sendRecv error: malformed HTTP response "15a1"
> 2017/07/07 19:55:03 SocketPipe 16 Close: pipe socket connections: 25
> 2017/07/07 19:55:03 duplexSendLoop: outbound stream closed
> 2017/07/07 19:55:03 SocketPipe 17 Close: pipe socket connections: 24
> 2017/07/07 19:55:03 SocketPipe 37 Close: pipe socket connections: 23
> 2017/07/07 19:55:03 SocketPipe 36 Close: pipe socket connections: 22
> 2017/07/07 19:55:03 SocketPipe Create: pipe socket connections: 24
> 2017/07/07 19:55:03 cmd connect
> 2017/07/07 19:55:03 sendRecv error: malformed HTTP response "159e"
> 2017/07/07 19:55:04 duplexRecvLoop: error roundTrip: write: connection reset by peer
> 2017/07/07 19:55:04 sendRecv error: remote error: tls: handshake failure
> 2017/07/07 19:55:04 sendRecv error: remote error: tls: handshake failure
> 2017/07/07 19:55:05 SocketPipe 23 Close: pipe socket connections: 23
> 2017/07/07 19:55:05 SocketPipe 22 Close: pipe socket connections: 22
> 2017/07/07 19:55:05 SocketPipe Create: pipe socket connections: 24
> 2017/07/07 19:55:05 cmd connect
> 2017/07/07 19:55:07 SocketPipe 23 Close: pipe socket connections: 23
> 2017/07/07 19:55:07 SocketPipe 22 Close: pipe socket connections: 22
> 2017/07/07 19:55:07 sendRecv error: remote error: tls: handshake failure
> 2017/07/07 19:55:07 sendRecv error: remote error: tls: handshake failure
> 2017/07/07 19:55:07 sendRecv error: malformed HTTP response "15a1"
> 2017/07/07 19:55:07 sendRecv error: malformed HTTP response "15a1"
> 2017/07/07 19:55:09 SocketPipe 22 Close: pipe socket connections: 21
> 2017/07/07 19:55:09 duplexSendLoop: outbound stream closed
> 2017/07/07 19:55:09 sendRecv error: malformed HTTP response "159e"
> 2017/07/07 19:55:09 SocketPipe 23 Close: pipe socket connections: 20
> 2017/07/07 19:55:10 sendRecv error: certificate name does not match: https://104.20.49.34:lbsportsinvestment.com
> 2017/07/07 19:55:10 sendRecv error: remote error: tls: handshake failure
> 2017/07/07 19:55:11 sendRecv error: malformed HTTP response "15a1"
> 2017/07/07 19:55:11 sendRecv error: remote error: tls: handshake failure
> 2017/07/07 19:55:12 sendRecv error: certificate name does not match: https://104.20.49.34:lbsportsinvestment.com
> 2017/07/07 19:55:12 sendRecv error: remote error: tls: handshake failure
> 2017/07/07 19:55:13 fail to finish a SYN request: i/o timeout
> 2017/07/07 19:55:13 SocketPipe 4 Close: pipe socket connections: 19
> 2017/07/07 19:55:13 fail to finish a SYN request: i/o timeout
> 2017/07/07 19:55:13 SocketPipe 20 Close: pipe socket connections: 18
> 2017/07/07 19:55:14 sendRecv error: malformed HTTP response "159e"
> 2017/07/07 19:55:14 duplexRecvLoop: error roundTrip: write: connection reset by peer
> 2017/07/07 19:55:14 fail to finish a SYN request: i/o timeout
> 2017/07/07 19:55:14 SocketPipe 0 Close: pipe socket connections: 17
> 2017/07/07 19:55:14 fail to finish a SYN request: i/o timeout
> 2017/07/07 19:55:14 SocketPipe 34 Close: pipe socket connections: 16
> 2017/07/07 19:55:15 sendRecv error: certificate name does not match: https://104.20.49.34:lbsportsinvestment.com
> 2017/07/07 19:55:15 fail to finish a SYN request: i/o timeout
> 2017/07/07 19:55:15 SocketPipe 28 Close: pipe socket connections: 15
> 2017/07/07 19:55:15 sendRecv error: EOF
> 2017/07/07 19:55:15 sendRecv error: EOF
> 2017/07/07 19:55:17 sendRecv error: certificate name does not match: https://104.20.49.34:lbsportsinvestment.com
> 2017/07/07 19:55:18 fail to finish a SYN request: i/o timeout
> 2017/07/07 19:55:18 SocketPipe 2 Close: pipe socket connections: 14
> 2017/07/07 19:55:19 fail to finish a SYN request: i/o timeout
> 2017/07/07 19:55:19 SocketPipe 8 Close: pipe socket connections: 13
> 2017/07/07 19:55:20 SocketPipe 30 Close: pipe socket connections: 12
> 2017/07/07 19:55:20 duplexSendLoop: outbound stream closed
> 2017/07/07 19:55:21 sendRecv error: malformed HTTP response "15a1"
> 2017/07/07 19:55:21 duplexRecvLoop: error roundTrip: write: connection reset by peer
> 2017/07/07 19:55:21 SocketPipe 31 Close: pipe socket connections: 11
> 2017/07/07 19:55:25 sendRecv error: malformed HTTP response "15a1"
> 2017/07/07 19:55:26 SocketPipe Create: pipe socket connections: 13
> 2017/07/07 19:55:26 cmd connect
> 2017/07/07 19:55:27 fail to finish a SYN request: i/o timeout
> 2017/07/07 19:55:27 SocketPipe 32 Close: pipe socket connections: 12
> 2017/07/07 19:55:34 SocketPipe 12 Close: pipe socket connections: 11
> 2017/07/07 19:55:34 SocketPipe 11 Close: pipe socket connections: 10
> 2017/07/07 19:55:34 SocketPipe Create: pipe socket connections: 12
> 2017/07/07 19:55:34 cmd connect
> 2017/07/07 19:55:37 SocketPipe 11 Close: pipe socket connections: 11
> 2017/07/07 19:55:37 SocketPipe 10 Close: pipe socket connections: 10
> 2017/07/07 19:55:37 SocketPipe Create: pipe socket connections: 12
> 2017/07/07 19:55:37 cmd connect
> 2017/07/07 19:55:39 SocketPipe 11 Close: pipe socket connections: 11
> 2017/07/07 19:55:39 SocketPipe 10 Close: pipe socket connections: 10
> 2017/07/07 19:55:39 SocketPipe Create: pipe socket connections: 12
> 2017/07/07 19:55:39 cmd connect
> 2017/07/07 19:57:40 duplexRecvLoop: error readResponse: read tcp 192.168.1.33:42620->104.16.38.170:443: i/o timeout
> 2017/07/07 19:57:40 SocketPipe 13 Close: pipe socket connections: 11
> 2017/07/07 19:57:40 SocketPipe 12 Close: pipe socket connections: 10
> 2017/07/07 19:57:40 SocketPipe 11 Close: pipe socket connections: 9
> 2017/07/07 19:57:40 SocketPipe 10 Close: pipe socket connections: 8

**Comment by yinghuocho** [comment]
之前的一个改动有bug，但是还是不知道为什么会导致CPU占用过高。刚刚更新了一个版本改回去了，请更新一下看看还有没有同样的问题。

**Comment by jzp820927** [comment]
想问下，Y 大 releases 的二进制文件，是用哪个版本的 go 编译的？

**Comment by yinghuocho** [comment]
1.8.3

**Comment by jzp820927** [comment]
哦，原来是最新稳定版，那应该和 go 没关系了。
