### ISSUE TITLE
付费成功后，购买记录却提示已取消

### ISSUE THREAD

**Issue by EndsVincent** [yinghuocho/firefly-proxy#552]
账号：493158376@qq.com

       开始下单的时候提示失败，再次尝试，购买成功！购买记录变成了待确认！过了一段时间后变成已取消！
       麻烦处理下，我一直在使用都是好好的，这对老的付费用户打击太大了。

**Comment by yinghuocho** [comment]
@EndsVincent  之前付费接口有点问题，查了一下你的付款记录，应该是确实没有扣费成功的，请确认。

**Comment by EndsVincent** [comment]
嗯，好的已经OK了
