### ISSUE TITLE
firefly如何配置全局代理？

### ISSUE THREAD

**Issue by turkeyB** [yinghuocho/firefly-proxy#79]
使用ubuntu的export http_proxy="http://127.0.0.1:38251/"指令 就可以执行出curl www.google.com的结果了。。。 可是为什么这时候没办法ping google呢？
如何设置才能让terminal也能访问google呢

**Comment by LuoZijun** [comment]
@turkeyB 

`ping` 使用的 `ICMP` 协议，大部分代理不会代理这个协议。

另外：

你使用 `export http_proxy="http://127.0.0.1:38251/"` 这种方式，并不是全局代理的设置方式。而仅仅只是写了一个环境变量，然后恰好 `curl` 支持这种环境变量读取。这个属于 `约定` 。

**Comment by turkeyB** [comment]
谢谢楼上

**Comment by zqfcoder** [comment]
win10呢

**Comment by LuoZijun** [comment]
@zqfcoder 

I've also run into issues with Win10 and socks. What worked for me was adding the socks proxy to the Internet Options in Control Panel (the old-school way of adding proxies to windows)

1. right click start -> control panel -> internet options -> connections tab -> LAN settings
2. Check off "Use a proxy server for your LAN..." -- Optionally, select "Bypass proxy server for local addresses"
3. Choose "Advanced"
4. enter in the IP and port (127.0.0.1 : <port#>) in the "Socks" fields, and leave the rest of them blank
5. Hit OK to save/exit out
6. Test with either browser

参考: https://www.reddit.com/r/techsupport/comments/4j0l35/windows_10_route_all_traffic_through_socks5_proxy/
