### ISSUE TITLE
Mac 系统连接起来时好时坏的 TAT

### ISSUE THREAD

**Issue by ryu2gaku** [yinghuocho/firefly-proxy#88]
如题

**Comment by yinghuocho** [comment]
是连不上，还是连上以后经常断？

**Comment by Dcfm** [comment]
@yinghuocho ubuntu 也是频繁的断线，经常就是上一分钟打开了谷歌，等会再去搜索就挂了。

**Comment by ryu2gaku** [comment]
@yinghuocho 同上，可以连上但是频繁断线

**Comment by ryu2gaku** [comment]
## 教材

### ▎文型

１）ここは　食堂です。  
２）エレベーターは　あそこです。
 
### ▎例文

１）ここは　新大阪ですか。  
・・・はい、そうです。  
２）トイレは　どこですか。  
・・・あそこです。  
３）山田さんは　どこですか。  
・・・会議室です。  
４）事務所は　どちらですか。  
・・・あちらです。  
５）[お]国は　どちらですか。  
・・・アメリカです。  
６）それは　どこの　靴ですか。  
・・・イタリアの　靴です。  
７）この　時計は　いくらですか。  
・・・18,600円です。

### ▎会話

**これを ください**

店員A：いらっしゃいませ。  
マリア：すみません。　ワイン売り場は　どこですか。  
店員A：地下１階です。  
マリア：どうも。

マリア：すみません。　その　ワインを　見せて　ください。  
店員B：はい、どうぞ。  
マリア：これは　どこの　ワインですか。  
店員B：日本のです。  
マリア：いくらですか。  
店員B：2,500円です。  
マリア：じゃ、これを　ください。

## 教案

### ▎目次

* [ここは〈場所〉です。](#section1)
* [〈場所・物・人〉はここです。](#section2)
* [〈場所・物・人〉は〈場所〉です。](#section3)
* [〈場所・物・人〉はこちらです。](#section4)
* [〈国・会社・大学〉は〜です。](#section5)
* [これは〈国名・会社名〉の〈物〉です。](#section6)（〈国名・会社名〉製の～）
* [～は～円です](#section7)

### <a id="section1"></a>▎ここは〈場所〉です。

ここは北海道です。  
そこはトイレです。  
あそこは受付です。

### <a id="section2"></a>▎〈場所・物・人〉はここです。

教室はここです。  
受付はそこです。  
駅はあそこです。

本はここです。  
時計はそこです。  
いすはあそこです。

先生はここです。  
トムさんはそこです。  
マリアさんはあそこです。

◆ Q：〜はどこですか

トイレはどこですか。  
・・・あそこです。

### <a id="section3"></a>▎〈場所・物・人〉は〈場所〉です。

学校は東京です。  
先生の家は千葉です。

ペンは教室です。

Sさんはトイレです。

会議室はどこですか。  
・・・8階です。

トニーさんの時計はどこですか。  
・・・受付です。

マイクさんはどこですか。  
・・・食堂です。

### <a id="section4"></a>▎〈場所・物・人〉はこちらです

◆ 丁寧な形

エスカレーターはこちらです。  
トイレはそちらです。  
受付はあちらです。

◆ Q：〜はどちらですか

会議室はどちらですか。  
・・・あちらです。

ロビーはどちらですか。  
・・・3階です。

### <a id="section5"></a>▎〈国・会社・大学〉は〜です。

☌ **出身国、所属の会社、学校、大学を尋ねる疑問詞**は「どこ」でもよいが、「みんなの日本語」は丁寧な形「**どちら**」になっている。  
☌「わたしのお国は～」と言ってしまう学生がいるので注意する。  
☌「会社（大学）はどちらですか」の場合、① 会社（大学）のある場所と、② 会社（大学）の名前を聞く２種類があるが、「みんなの日本語」で扱う練習は②の会社名（大学名）のみ。

わたしの国は日本です。  
カオサイさんのお国はタイです。  
カーンさんの会社はドイツ自動車です。  
マイクさんの大学は日本大学です。

◆ Q：お国・会社・大学はどちらですか 

レベッカさんのお国はどちらですか。  
・・・アメリカです。

シュルツさんの会社はどちらですか。  
・・・シュコダ自動車です。

トニーさんの大学はどちらですか。  
・・・シドニー大学です。

### <a id="section6"></a>▎これは〈国名・会社名〉の〈物〉です。

◆ 物の生産国、会社（メーカー）

これは日本の時計です。  
これはトヨタの車です。  
それは台湾のパソコンです。  
それはASUSのパソコンです。

◆ Q：～はどこの〈物〉ですか

これはどこの車ですか  
・・・イタリアの車です。  
・・・フェラーリの車です。

### <a id="section7"></a>▎～は〜円です。

◆ 値段

この鉛筆は５０円です。  
このノートは１００円です。

◆ Q：～はいくらですか

この時計はいくらですか。  
・・・4,300円です。

### ▎会話練習

A：すみません、食堂はどこですか。  
B：そこです。  
A：ありがとうございます。

A：お国はどちらですか。  
B：イタリアです。  
A：うちはどちらですか。  
B：ローマです。  
A：そうですか。

A：すみません。それはどこの車ですか。  
B：これはドイツの車です。  
A：いくらですか。  
B：780,000円です。

**Comment by ryu2gaku** [comment]
## 教材

### ▎文型

１）今　4時5分です。  
２）わたしは　毎朝　6時に　起きます。  
３）わたしは　きのう　勉強しました。

### ▎例文

１）今　何時ですか。  
・・・2時10分です。  
ニューヨークは　今　何時ですか。  
・・・午前　0時10分です。

２）休みは　何曜日ですか。  
・・・土曜日と　日曜日です。

３）アップル銀行は　何時から　何時までですか。  
・・・9時から　3時までです。

４）毎晩　何時に　寝ますか。  
・・・11時に　寝ます。

５）毎日　何時から　何時まで　勉強しますか。  
・・・朝　9時から　午後　3時まで　勉強します。

６）土曜日　働きますか。  
・・・いいえ、働きません。

７）きのう　勉強しましたか。  
・・・いいえ、勉強しませんでした。

### ▎会話

**そちらは 何時から 何時までですか**

ミラー：すみません、「あすか」の　電話番号は　何番ですか。  
佐藤：「あすか」ですか。　5275の　2725です。  
ミラー：どうも　ありがとう　ございます。

店の人：はい、「あすか」です。  
ミラー：すみません。　そちらは　何時までですか。  
店の人：10時までです。  
ミラー：休みは　何曜日ですか。  
店の人：日曜日です。  
ミラー：そうですか。　どうも。

## 教案

### ▎目次

* [～時～分です。](#section1)
* [～は～曜日です。](#section2)
* [～は～時から～時までです。](#section3)
* [～時に～ます。](#section4)
* [～から～まで～ます。](#section5)
* [～ます・～ません・～ました・～ませんでした](#section6)
* [電話番号](#section7)





###  <a id="section1"></a>▎～時～分です。

今４時です。  
今１２時半です。  
今８時４０分です。  
今午前６時５５分です。  
今午後７時２３分です。

大阪は今何時ですか。  
・・・午後７時です。

ロンドンは今何時ですか。  
・・・午前１２時２０分です。

### <a id="section2"></a>▎～曜日です。

今日は水曜日です。  
明日は木曜日です。  
休みは日曜日です。  
休みは土曜日と日曜日です。

休みは何曜日ですか。  
・・・日曜日です。

会議は何曜日ですか。  
・・・月曜日です。

### <a id="section3"></a>▎～は～時から～時までです。

昼休みは１時から２時までです。  
会議は午前１１時から午後２時までです。  
日本の銀行は午前９時から午後３時までです。

デパートは何時から何時までですか。  
・・・１０時から５時半までです。

図書館は何時から何時までですか。  
・・・午前９時から午後３時までです。

### <a id="section4"></a>▎～時に～ます。

わたしは毎日８時に起きます。  
マリアさんは毎晩１１時に寝ます。  
トムさんは毎朝７時半に起きます。

ジミーさんは毎日何時に起きますか。  
・・・７時に起きます。

山田さんは今晩何時に寝ますか。  
・・・午後１０時に寝ます。

毎日何時に起きますか。  
・・・７時に起きます。

### <a id="section5"></a>▎～から～まで～ます。

マリアさんは１２時から７時まで寝ます。  
ワンさんは９時から５時まで働きます。

ミラーさんは何時から何時まで勉強しますか。  
・・・６時から７時まで勉強します。

金曜日何時から何時まで働きますか。  
・・・９時から３時まで働きます。

カオサイさんは何時から何時まで働きますか。  
・・・午前８時半から午後５時まで働きます。

毎晩何時から何時まで寝ますか。  
・・・２時から５時まで寝ます。

### <a id="section6"></a>▎～ます・～ません・～ました・～ませんでした

明日働きます。  
毎日トムさんは勉強します。

きのう寝ました。  
おとといケンさんは休みました。

明日休みません。  
あさってイムさんは働きません。

おととい寝ませんでした。  
きのうミックさんは勉強しませんでした。

あさって休みますか。  
・・・はい、休みます。  
・・・いいえ、休みません。

きのう寝ましたか。  
・・・はい、寝ました。  
・・・いいえ、寝ませんでした。

### <a id="section7"></a>▎電話番号

あさひデパートの電話番号は123-5456です。  
市役所の電話番号は02-2234-5559です。

にじいろスーパーの電話番号は何番ですか。  
・・・33-4456です。

### ▎会話練習

A：図書館は何時から何時までですか。  
B：９時から５時までです。  
A：休みは何曜日ですか。  
B：日曜日です。

A：すみません、会議は何時からですか。  
B：９時からです。  
A：何時に終わりますか。  
B：１０時に終わります。  
A：わかりました。

A：きのう１０時まで勉強しました。  
B：何時に寝ましたか。  
A：１２時に寝ました。  
B：大変ですね。

**Comment by ryu2gaku** [comment]
### ▎2019 年 5 月 21 日（火）晴

**#省考成绩#**

湖北省省考的成绩出来了，我人生第一次省考的行测和申论的得分分别是 57.6+47.5=105.1。行测的数量关系和资料分析因为答题时间不够的关系，简单粗暴地直接填涂答题卡。申论部分最后的作文，脑部整个放空，实在是编不出来，抄文字材料凑字数都抄到心虚的程度，最后也没凑满字数。所以这次的分数有些超出我的预期。

同期考试的其他人分享的情况：周悬松 52.6+63.5=116.1、方震 48.8+61.5=110.3、廖宇 55.2+50=105.2、吴翔 34.4+62.5=96.9

### ▎2019 年 5 月 22 日（水）晴

时光荏苒，来法院执行局工作已经快满两年了，政治处早上过来下通知，满两年且考核合格的聘用人员，月工资在原工资基础上增加 300 元。

### ▎2019 年 5 月 24 日（金）晴

**#执行局部门改革#**

快到周末了，回顾这一周，最初内心深处有股淡淡的失落感，现在也已经慢慢地习惯了所有的改变。执行局在这一周正式地部门改革，待了快两年的裁决庭在周一吃完散伙饭后，成为了过往的记忆，念及此唏嘘不已。现在的执行局下设执行指挥中心和执行实施团队，执行实施团队又分为简易案件执行组和普通案件执行组。我被编入了普通案件执行组，作为一颗小小的螺丝钉，目前还暂时没有工作形式上变动的最直观感受。

### ▎2019 年 5 月 25 日（土）暴雨

**#庆祝改革开放 40 周年普通纪念币#**

大概在三月份的时候在网上预定了 20 枚庆祝改革开放 40 周年普通纪念币，兑换期截止到明天。早上九点钟骑着自行车出门，来到位于长安大道 52 号的中国银行咸宁咸安支行办理兑换，没有想象中大排长龙的场景，稍等了片刻就入手成功。然后顺势来到附近青龙路的一家北京骨头汤面店，这家店过早的人很多，食物的价格也比起其他的早餐店贵些许，味道还算得上对口。买了一碗牛肉面、两个面窝和一杯豆浆，这时候的天空雷声隐隐，已然预示着有一场暴风雨即将来临。不敢在此多作停留，快速消灭完手边的食物，迎着还未声势浩大的细雨直冲回家。

### ▎2019 年 5 月 27 日（月）晴

今晚叶辉在天丽宾馆二楼的老位置请客聚餐，每次这种饭局总是少不了劝酒，结果没能吃太多内容，肚子就先让啤酒撑爆了，回到家后一个钟头内跑了五六趟厕所。

### ▎2019 年 5 月 31 日（金）晴

**#王明求婚#**

横沟法庭的王明打算今晚向女友求婚，好几天前就在微信群里约聚。下班后我跟着方震和廖宇，坐着袁博的车先去怀德路的美音 KTV 帮忙布置告白的场地。由于时间过于匆急，只是简单的用气球装饰一下包房，并在门口的位置用蜡烛围出一个桃心。接着就赶往银泉大道的米德尔酒店二楼吃饭，到场的算我在内一共十四人，由于大家有些放不开，饭桌的气氛并不是很活跃。接着照着剧本吃完饭回到 KTV，KTV 的负责人怕点蜡烛的烟可能会触发房间的防火水幕，要求我们只能点燃几分钟蜡烛。
